language: node_js
node_js:
  - "8"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"
git:
  depth: 5
install:
  - yarn install
  - yarn build
script:
  - yarn lint
  - yarn test
  - yarn run test:cov:ci
  - yarn run test:mutation
