language: node_js
node_js:
  - "8"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"
git:
  depth: 5
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - yarn install
  - yarn build
script:
  - yarn lint
  - yarn test
  - yarn run test:cov:ci
  - yarn run test:mutation
